### ISSUE TITLE
Fehler darkmode

### ISSUE THREAD

**Issue by WetTiger** [mstoeb2s/Impfungen-Deutschland#1]
Hi, I’m darkmode ist das widget bis auf die Zahlen leider nicht mehr lesbar...

**Comment by mstoeb2s** [comment]
Ich bin auch im dark-Modus. Manchmal braucht es einen Moment um sich umzustellen. 

![image](https://user-images.githubusercontent.com/73257648/103704718-057c5100-4faa-11eb-9145-c41d9b427fae.jpeg)

**Comment by WetTiger** [comment]
Leider auch nach 1-2 Minuten warten keine Änderung. Wenn das Script innerhalb Scriptable läuft geht’s. Auf dem homescreen nicht...
![0221EBB1-C8ED-46F0-A38C-FB8E4C2327DA](https://user-images.githubusercontent.com/76124896/103747551-21601100-5003-11eb-89b2-b46c8e59afa1.jpeg)

**Comment by mstoeb2s** [comment]
Du kannst auch direkt die Farbe im Skript anpassen. Ist ja nur für die zwei Zeilen. 
Bei mir klappt das ohne Problem 🧐
