### ISSUE TITLE
Sachsen und Sachsen-Anhalt sind vertauscht

### ISSUE THREAD

**Issue by ooottttooo** [mstoeb2s/Impfungen-Deutschland#2]
Die Werte und Einwohnerzahlen sind irgendwie verdreht.
Wenn ich als BL 12 eingebe, kriege ich die Impfzahlen von Sachsen, nicht Sachsen-Anhalt

ansonsten sehr schön, danke!

**Comment by mstoeb2s** [comment]
Ist erledigt! Danke für den Hinweis!
